version: '3'

networks:
  ampaba:

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx_ampaba
    ports: 
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - ampaba

  mysql:
    image: mysql:5.6.43
    container_name: mysql_ampaba
    restart: unless-stopped
    tty: true
    ports: 
    - "5643:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: starfit
      MYSQL_USER: herlandy
      MYSQL_PASSWORD: herlandy29
      MYSQL_ROOT_PASSWORD: herlandy29
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
     - ampaba

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_ampaba
    volumes:
        - ./src:/var/www/html
        - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
        - "9000:9000"
    networks:
      - ampaba
      # - besimdocker_app-shared
